const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),T=require('./dist/engine.js');
const root=path.join(__dirname,'dist'),dataDir=process.env.CUP_DATA_DIR||path.join(__dirname,'data'),stateFile=path.join(dataDir,'tournament.json'),legacyAuthFile=path.join(dataDir,'auth.json'),accountsFile=path.join(dataDir,'accounts.json'),accessFile=path.join(dataDir,'admin-access.txt');
fs.mkdirSync(dataDir,{recursive:true});
const empty=()=>({players:[],rounds:null,log:[],revision:0,modePool:['draft','triple']});
let state=fs.existsSync(stateFile)?JSON.parse(fs.readFileSync(stateFile,'utf8')):empty();
const makeSecret=password=>{const salt=crypto.randomBytes(16).toString('hex');return{salt,hash:crypto.scryptSync(password,salt,64).toString('hex')}},randomPassword=()=>crypto.randomBytes(18).toString('base64url'),normalizeLogin=value=>String(value||'').trim().toLowerCase(),validLogin=value=>/^[a-z0-9_.-]{3,24}$/.test(value),validPassword=value=>typeof value==='string'&&value.length>=8&&value.length<=256;
function verify(password,account){if(typeof password!=='string'||password.length>256)return false;const actual=crypto.scryptSync(password,account.salt,64),expected=Buffer.from(account.hash,'hex');return actual.length===expected.length&&crypto.timingSafeEqual(actual,expected)}
function initializeAccounts(){if(fs.existsSync(accountsFile))return JSON.parse(fs.readFileSync(accountsFile,'utf8'));let firstSecret,firstPassword='';if(fs.existsSync(legacyAuthFile))firstSecret=JSON.parse(fs.readFileSync(legacyAuthFile,'utf8'));else{firstPassword=randomPassword();firstSecret=makeSecret(firstPassword)}if(!firstPassword&&fs.existsSync(accessFile)){const text=fs.readFileSync(accessFile,'utf8');firstPassword=text.match(/Пароль администратора:\s*(\S+)/)?.[1]||''}const secondPassword=randomPassword(),data={version:1,users:[{id:crypto.randomUUID(),login:'organizer1',role:'organizer',...firstSecret},{id:crypto.randomUUID(),login:'organizer2',role:'organizer',...makeSecret(secondPassword)}]};fs.writeFileSync(accountsFile,JSON.stringify(data),{mode:0o600});const firstLine=firstPassword?`Логин: organizer1\nПароль: ${firstPassword}`:'Логин: organizer1\nПароль: используйте ранее установленный пароль';fs.writeFileSync(accessFile,`Аккаунты организаторов\n\n1) ${firstLine}\n\n2) Логин: organizer2\nПароль: ${secondPassword}\n\nХраните этот файл у себя. Он не доступен через сайт.\n`,{mode:0o600});return data}
let accounts=initializeAccounts();
const sessions=new Map(),attempts=new Map(),registrations=new Map(),duration=8*60*60*1000;
function atomicWrite(file,value){fs.writeFileSync(file+'.tmp',JSON.stringify(value),{mode:0o600});fs.renameSync(file+'.tmp',file)}
function persist(next){next.revision=state.revision+1;atomicWrite(stateFile,next);state=next}
function persistAccounts(next){atomicWrite(accountsFile,next);accounts=next}
function fail(message,status=400){throw Object.assign(new Error(message),{status})}
function currentSession(req){const token=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('cup_session='))?.slice(12),value=sessions.get(token);return value&&value.expires>Date.now()?{...value,token}:null}
function cookie(token,age){return`cup_session=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=${age}${process.env.CUP_SECURE_COOKIE==='1'?'; Secure':''}`}
function identity(s){return s?{role:s.role,login:s.login,playerId:s.playerId||null}:null}
function publicState(s){const linked=new Set(accounts.users.filter(x=>x.role==='participant'&&x.playerId).map(x=>x.playerId));return{...state,players:state.players.map(p=>({...p,hasAccount:linked.has(p.id)})),log:s?.role==='organizer'?state.log:[]}}
function responsePayload(s){return{state:publicState(s),viewer:identity(s),admin:s?.role==='organizer'}}
function send(res,status,data,headers={}){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...headers});res.end(JSON.stringify(data))}
async function body(req){let text='';for await(const chunk of req){text+=chunk;if(Buffer.byteLength(text)>16384)fail('Слишком большой запрос',413)}try{return JSON.parse(text)}catch{fail('Некорректный запрос')}}
function throttle(map,key,limit,windowMs){const now=Date.now();let item=map.get(key);if(!item||item.until<now)item={count:0,until:now+windowMs};map.set(key,item);if(item.count>=limit)fail('Слишком много попыток. Попробуйте позже.',429);item.count++}
function event(next,text){next.log.unshift({text,time:new Date().toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})});next.log=next.log.slice(0,200)}
function friendship(b){const friendCode=typeof b.friendCode==='string'?b.friendCode.trim():'',friendLink=typeof b.friendLink==='string'?b.friendLink.trim():'';if(friendCode.length>80||/[\x00-\x1f]/.test(friendCode)||friendLink.length>1000)fail('Проверьте данные для дружбы');if(!friendCode&&!friendLink)fail('Добавьте код дружбы или ссылку приглашения');if(friendLink){let u;try{u=new URL(friendLink)}catch{fail('Нужна полная ссылка приглашения')}if(u.protocol!=='https:'||!['link.clashroyale.com','link.supercell.com','id.supercell.com'].includes(u.hostname)||u.username||u.password||u.port)fail('Разрешены только ссылки приглашения Clash Royale или Supercell')}return{friendCode,friendLink}}
function playerFields(b,exceptId=null){const name=typeof b.name==='string'?b.name.trim():'',nick=typeof b.nick==='string'?b.nick.trim():'',tag=typeof b.tag==='string'?'#'+b.tag.trim().replace(/^#/,'').toUpperCase():'';if(!name||name.length>50||!nick||nick.length>40||!/^#[A-Z0-9]{3,19}$/.test(tag))fail('Проверьте имя, ник и тег игрока');if(state.players.some(p=>p.id!==exceptId&&p.tag===tag))fail('Игрок с таким тегом уже зарегистрирован');return{name,nick,tag,...friendship(b)}}
function requireOrganizer(s){if(s?.role!=='organizer')fail('Войдите как организатор',401)}
function change(b){if(b.revision!==state.revision)fail('Данные уже изменились. Обновили страницу — повторите действие.',409);const next=structuredClone(state);switch(b.action){
case'modes':if(!Array.isArray(b.pool)||!b.pool.length||b.pool.length>2||b.pool.some(x=>!['draft','triple'].includes(x))||new Set(b.pool).size!==b.pool.length)fail('Оставьте хотя бы один режим');next.modePool=b.pool;event(next,'Обновлён пул режимов');break;
case'friend':{const p=next.players.find(p=>p.id===b.id);if(!p)fail('Участник не найден');Object.assign(p,friendship(b));event(next,'Обновлены данные для дружбы');break}
case'seed':{if(next.rounds)fail('Регистрация закрыта');const offset=next.players.length;for(let i=0;i<9;i++)next.players.push({id:crypto.randomUUID(),name:`Демо ${offset+i+1}`,nick:`Игрок ${offset+i+1}`,tag:`#DEMO${offset+i+1}`,friendCode:`DEMO${offset+i+1}`});event(next,'Добавлены 9 тестовых участников');break}
case'remove':if(next.rounds)fail('Состав зафиксирован');if(!next.players.some(p=>p.id===b.id))fail('Участник не найден');next.players=next.players.filter(p=>p.id!==b.id);{const a=structuredClone(accounts);a.users=a.users.filter(x=>x.playerId!==b.id);persistAccounts(a)}event(next,'Участник удалён');break;
case'generate':if(next.rounds)fail('Сетка уже создана');next.rounds=T.generate(next.players);event(next,'Сетка создана случайной жеребьёвкой');break;
case'regenerate':if(!next.rounds||next.rounds.flat().some(m=>['live','done'].includes(m.status)))fail('Матчи уже начались');next.rounds=null;event(next,'Регистрация открыта повторно');break;
case'reset':next.players=[];next.rounds=null;next.log=[];{const a=structuredClone(accounts);a.users=a.users.filter(x=>x.role==='organizer');persistAccounts(a)}event(next,'Турнир сброшен');break;
case'start':case'result':case'game':case'note':{const r=b.r,i=b.i;if(!Number.isInteger(r)||!Number.isInteger(i)||!next.rounds?.[r]?.[i])fail('Матч не найден');const m=next.rounds[r][i];if(!m.p.every(Boolean)||m.status==='bye')fail('Соперники ещё не определены');if(b.note!==undefined&&(typeof b.note!=='string'||b.note.length>500))fail('Описание: не более 500 символов');if(b.action==='start'){if(m.status!=='waiting'&&!(m.status==='live'&&!m.mode))fail('Матч уже начался');m.modePool=[...(next.modePool||['draft','triple'])];m.mode=m.modePool[crypto.randomInt(m.modePool.length)];m.revealAt=Date.now()+4000;m.startedAt=new Date().toISOString();m.status='live';m.score=[0,0];m.games=[];event(next,`Начат матч ${r+1}.${i+1}; режим: ${m.mode}`)}else if(b.action==='note'){m.note=b.note||'';event(next,`Описание матча ${r+1}.${i+1} обновлено`)}else if(b.action==='game'){if(m.status!=='live'||!m.mode)fail('Сначала начните матч');if(Date.now()<m.revealAt)fail('Дождитесь завершения рулетки');if(![0,1].includes(b.winner))fail('Выберите победителя боя');m.score=m.score||[0,0];m.score[b.winner]++;m.games=m.games||[];m.games.push({winner:m.p[b.winner],at:new Date().toISOString()});const target=r===next.rounds.length-1?3:2;if(m.score[b.winner]===target){T.result(next.rounds,r,i,...m.score);m.completedAt=new Date().toISOString()}event(next,`Бой матча ${r+1}.${i+1}: ${m.score.join(':')}`)}else{if(!b.technical&&(m.status==='waiting'||Date.now()<m.revealAt))fail('Сначала начните матч и дождитесь режима');T.result(next.rounds,r,i,b.a,b.b,b.technical===true);m.games=[];m.note=b.note===undefined?(m.note||''):b.note;m.completedAt=new Date().toISOString();event(next,`Матч ${r+1}.${i+1}: ${b.a}:${b.b}`)}break}
default:fail('Неизвестное действие')}persist(next)}
const server=http.createServer(async(req,res)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','same-origin');res.setHeader('X-Frame-Options','DENY');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self'; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'");try{const port=process.env.PORT||4173,origin=process.env.CUP_ORIGIN||`http://127.0.0.1:${port}`;if(req.headers.host!==new URL(origin).host)fail('Недопустимый адрес',403);const url=new URL(req.url,origin),s=currentSession(req);
if(url.pathname.startsWith('/api/')){if(req.method==='GET'&&url.pathname==='/api/state')return send(res,200,responsePayload(s));if(req.method!=='POST')fail('Метод недоступен',405);if(req.headers.origin!==origin||!req.headers['content-type']?.startsWith('application/json'))fail('Недопустимый источник запроса',403);const b=await body(req),ip=req.socket.remoteAddress;
if(url.pathname==='/api/login'){throttle(attempts,ip,8,15*60*1000);const login=normalizeLogin(b.login||'organizer1'),account=accounts.users.find(a=>a.login===login),dummy=account||{salt:'0'.repeat(32),hash:crypto.scryptSync('dummy','0'.repeat(32),64).toString('hex')};if(!verify(b.password,dummy)||!account)fail('Неверный логин или пароль',401);attempts.delete(ip);if(s)sessions.delete(s.token);const token=crypto.randomBytes(32).toString('base64url');sessions.set(token,{accountId:account.id,login:account.login,role:account.role,playerId:account.playerId||null,expires:Date.now()+duration});return send(res,200,responsePayload(sessions.get(token)),{'Set-Cookie':cookie(token,duration/1000)})}
if(url.pathname==='/api/logout'){if(s)sessions.delete(s.token);return send(res,200,responsePayload(null),{'Set-Cookie':cookie('',0)})}
if(url.pathname==='/api/register'){throttle(registrations,ip,20,60*60*1000);if(state.rounds)fail('Регистрация закрыта');const login=normalizeLogin(b.login);if(!validLogin(login))fail('Логин: 3–24 латинских символа, цифры, точка, дефис или подчёркивание');if(!validPassword(b.password))fail('Пароль: от 8 до 256 символов');if(accounts.users.some(a=>a.login===login))fail('Этот логин уже занят');const fields=playerFields(b),player={id:crypto.randomUUID(),...fields},account={id:crypto.randomUUID(),login,role:'participant',playerId:player.id,...makeSecret(b.password)},nextAccounts=structuredClone(accounts),next=structuredClone(state);nextAccounts.users.push(account);next.players.push(player);persistAccounts(nextAccounts);persist(next);const token=crypto.randomBytes(32).toString('base64url');sessions.set(token,{accountId:account.id,login,role:'participant',playerId:player.id,expires:Date.now()+duration});return send(res,200,responsePayload(sessions.get(token)),{'Set-Cookie':cookie(token,duration/1000)})}
if(url.pathname==='/api/profile'){if(s?.role!=='participant'||!s.playerId)fail('Войдите как участник',401);const index=state.players.findIndex(p=>p.id===s.playerId);if(index<0)fail('Профиль участника не найден',404);const next=structuredClone(state);next.players[index]={...next.players[index],...playerFields(b,s.playerId)};persist(next);return send(res,200,responsePayload(s))}
if(url.pathname==='/api/accounts/set'){requireOrganizer(s);const player=state.players.find(p=>p.id===b.playerId);if(!player)fail('Участник не найден');const login=normalizeLogin(b.login);if(!validLogin(login))fail('Логин: 3–24 латинских символа, цифры, точка, дефис или подчёркивание');if(!validPassword(b.password))fail('Пароль: от 8 до 256 символов');const existing=accounts.users.find(a=>a.playerId===player.id);if(accounts.users.some(a=>a.login===login&&a.id!==existing?.id))fail('Этот логин уже занят');const next=structuredClone(accounts),target=next.users.find(a=>a.playerId===player.id);if(target)Object.assign(target,{login,...makeSecret(b.password)});else next.users.push({id:crypto.randomUUID(),login,role:'participant',playerId:player.id,...makeSecret(b.password)});if(existing)for(const[token,value]of sessions)if(value.accountId===existing.id)sessions.delete(token);persistAccounts(next);return send(res,200,responsePayload(s))}
if(url.pathname==='/api/password'){if(!s)fail('Сначала войдите',401);const account=accounts.users.find(a=>a.id===s.accountId);if(!account||!verify(b.current,account))fail('Текущий пароль неверен');if(!validPassword(b.password))fail('Новый пароль: от 8 до 256 символов');const next=structuredClone(accounts);Object.assign(next.users.find(a=>a.id===account.id),makeSecret(b.password));persistAccounts(next);for(const[token,value]of sessions)if(value.accountId===account.id)sessions.delete(token);return send(res,200,responsePayload(null),{'Set-Cookie':cookie('',0)})}
requireOrganizer(s);if(url.pathname==='/api/action'){change(b);return send(res,200,responsePayload(s))}fail('Не найдено',404)}
if(!['GET','HEAD'].includes(req.method))fail('Метод недоступен',405);const files={'/':'index.html','/index.html':'index.html','/app.js':'app.js','/style.css':'style.css','/engine.js':'engine.js','/brand.png':'brand.png'},file=files[url.pathname];if(!file)fail('Не найдено',404);const data=fs.readFileSync(path.join(root,file));res.setHeader('Cache-Control','no-cache');res.setHeader('Content-Type',file.endsWith('.html')?'text/html; charset=utf-8':file.endsWith('.css')?'text/css; charset=utf-8':file.endsWith('.png')?'image/png':'text/javascript; charset=utf-8');res.end(req.method==='HEAD'?undefined:data)}catch(err){send(res,err.status||400,{error:err.status===500?'Ошибка сервера':err.message})}});
setInterval(()=>{const now=Date.now();for(const[k,v]of sessions)if(v.expires<now)sessions.delete(k);for(const map of[attempts,registrations])for(const[k,v]of map)if(v.until<now)map.delete(k)},60000).unref();
server.listen(process.env.PORT||4173,'127.0.0.1',()=>console.log(`Local: http://127.0.0.1:${process.env.PORT||4173}`));

