const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const T=require('./dist/engine.js'),root=path.join(__dirname,'dist'),dataDir=process.env.CUP_DATA_DIR||path.join(__dirname,'data');
fs.mkdirSync(dataDir,{recursive:true});const stateFile=path.join(dataDir,'tournament.json'),authFile=path.join(dataDir,'auth.json');
if(!fs.existsSync(authFile)){const password=crypto.randomBytes(18).toString('base64url'),salt=crypto.randomBytes(16).toString('hex');fs.writeFileSync(authFile,JSON.stringify({salt,hash:crypto.scryptSync(password,salt,64).toString('hex')}),{mode:0o600});fs.writeFileSync(path.join(dataDir,'admin-access.txt'),`Пароль администратора: ${password}\n\nВход: кнопка «Организатор» на сайте.\nХраните этот файл у себя. Он не доступен через сайт.\n`,{mode:0o600})}
let credentials=JSON.parse(fs.readFileSync(authFile,'utf8'));const empty=()=>({players:[],rounds:null,log:[],revision:0,modePool:['draft','triple']});let state=fs.existsSync(stateFile)?JSON.parse(fs.readFileSync(stateFile,'utf8')):empty();
const sessions=new Map(),attempts=new Map(),registrations=new Map(),duration=8*60*60*1000;
function persist(next){next.revision=state.revision+1;fs.writeFileSync(stateFile+'.tmp',JSON.stringify(next));fs.renameSync(stateFile+'.tmp',stateFile);state=next}
function fail(message,status=400){throw Object.assign(new Error(message),{status})}
function session(req){const token=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('cup_session='))?.slice(12);const s=sessions.get(token);return s&&s.expires>Date.now()?{...s,token}:null}
function cookie(token,age){return `cup_session=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=${age}${process.env.CUP_SECURE_COOKIE==='1'?'; Secure':''}`}
function send(res,status,data,headers={}){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...headers});res.end(JSON.stringify(data))}
function view(isAdmin){return {...state,log:isAdmin?state.log:[]}}
async function body(req){let text='';for await(const chunk of req){text+=chunk;if(Buffer.byteLength(text)>16384)fail('Слишком большой запрос',413)}try{return JSON.parse(text)}catch{fail('Некорректный запрос')}}
function throttle(map,key,limit,windowMs){const now=Date.now();let item=map.get(key);if(!item||item.until<now)item={count:0,until:now+windowMs};map.set(key,item);if(item.count>=limit)fail('Слишком много попыток. Попробуйте позже.',429);item.count++}
function event(next,text){next.log.unshift({text,time:new Date().toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})});next.log=next.log.slice(0,200)}
function friendship(b){const friendCode=typeof b.friendCode==='string'?b.friendCode.trim():'',friendLink=typeof b.friendLink==='string'?b.friendLink.trim():'';if(friendCode.length>80||/[\x00-\x1f]/.test(friendCode)||friendLink.length>1000)fail('Проверьте данные для дружбы');if(!friendCode&&!friendLink)fail('Добавьте код дружбы или ссылку приглашения');if(friendLink){let u;try{u=new URL(friendLink)}catch{fail('Нужна полная ссылка приглашения')}if(u.protocol!=='https:'||!['link.clashroyale.com','link.supercell.com','id.supercell.com'].includes(u.hostname)||u.username||u.password||u.port)fail('Разрешены только ссылки приглашения Clash Royale или Supercell')}return {friendCode,friendLink}}
function change(b){if(b.revision!==state.revision)fail('Данные уже изменились. Обновили страницу — повторите действие.',409);const next=structuredClone(state);switch(b.action){
case 'modes':if(!Array.isArray(b.pool)||!b.pool.length||b.pool.length>2||b.pool.some(x=>!['draft','triple'].includes(x))||new Set(b.pool).size!==b.pool.length)fail('Оставьте хотя бы один режим');next.modePool=b.pool;event(next,'Обновлён пул режимов');break;
case 'friend':{const p=next.players.find(p=>p.id===b.id);if(!p)fail('Участник не найден');Object.assign(p,friendship(b));event(next,'Обновлены данные для дружбы');break}
case 'seed': {if(next.rounds)fail('Регистрация закрыта');const offset=next.players.length;for(let i=0;i<9;i++)next.players.push({id:crypto.randomUUID(),name:`Демо ${offset+i+1}`,nick:`Игрок ${offset+i+1}`,tag:`#DEMO${offset+i+1}`,friendCode:`DEMO${offset+i+1}`});event(next,'Добавлены 9 тестовых участников');break}
case 'remove':if(next.rounds)fail('Состав зафиксирован');if(!next.players.some(p=>p.id===b.id))fail('Участник не найден');next.players=next.players.filter(p=>p.id!==b.id);event(next,'Участник удалён');break;
case 'generate':if(next.rounds)fail('Сетка уже создана');next.rounds=T.generate(next.players);event(next,'Сетка создана случайной жеребьёвкой');break;
case 'regenerate':if(!next.rounds||next.rounds.flat().some(m=>['live','done'].includes(m.status)))fail('Матчи уже начались');next.rounds=null;event(next,'Регистрация открыта повторно');break;
case 'reset':next.players=[];next.rounds=null;next.log=[];event(next,'Турнир сброшен');break;
case 'start':case 'result':case 'game':case 'note': {const r=b.r,i=b.i;if(!Number.isInteger(r)||!Number.isInteger(i)||!next.rounds?.[r]?.[i])fail('Матч не найден');const m=next.rounds[r][i];if(!m.p.every(Boolean)||m.status==='bye')fail('Соперники ещё не определены');if(b.note!==undefined&&(typeof b.note!=='string'||b.note.length>500))fail('Описание: не более 500 символов');
if(b.action==='start'){if(m.status!=='waiting'&&!(m.status==='live'&&!m.mode))fail('Матч уже начался');m.modePool=[...(next.modePool||['draft','triple'])];m.mode=m.modePool[crypto.randomInt(m.modePool.length)];m.revealAt=Date.now()+4000;m.startedAt=new Date().toISOString();m.status='live';m.score=[0,0];m.games=[];event(next,`Начат матч ${r+1}.${i+1}; режим: ${m.mode}`)}
else if(b.action==='note'){m.note=b.note||'';event(next,`Описание матча ${r+1}.${i+1} обновлено`)}
else if(b.action==='game'){if(m.status!=='live'||!m.mode)fail('Сначала начните матч');if(Date.now()<m.revealAt)fail('Дождитесь завершения рулетки');if(![0,1].includes(b.winner))fail('Выберите победителя боя');m.score=m.score||[0,0];m.score[b.winner]++;m.games=m.games||[];m.games.push({winner:m.p[b.winner],at:new Date().toISOString()});const target=r===next.rounds.length-1?3:2;if(m.score[b.winner]===target){T.result(next.rounds,r,i,...m.score);m.completedAt=new Date().toISOString()}event(next,`Бой матча ${r+1}.${i+1}: ${m.score.join(':')}`)}
else{if(!b.technical&&(m.status==='waiting'||Date.now()<m.revealAt))fail('Сначала начните матч и дождитесь режима');T.result(next.rounds,r,i,b.a,b.b,b.technical===true);m.games=[];m.note=b.note===undefined?(m.note||''):b.note;m.completedAt=new Date().toISOString();event(next,`Матч ${r+1}.${i+1}: ${b.a}:${b.b}`)}break}
default:fail('Неизвестное действие')}
persist(next)}
const server=http.createServer(async(req,res)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','same-origin');res.setHeader('X-Frame-Options','DENY');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self'; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'");try{
const port=process.env.PORT||4173,origin=process.env.CUP_ORIGIN||`http://127.0.0.1:${port}`;if(req.headers.host!==new URL(origin).host)fail('Недопустимый адрес',403);const url=new URL(req.url,origin),s=session(req);
if(url.pathname.startsWith('/api/')){
if(req.method==='GET'&&url.pathname==='/api/state')return send(res,200,{state:view(!!s),admin:!!s});
if(req.method!=='POST')fail('Метод недоступен',405);
if(req.headers.origin!==origin||!req.headers['content-type']?.startsWith('application/json'))fail('Недопустимый источник запроса',403);
const b=await body(req),ip=req.socket.remoteAddress;
if(url.pathname==='/api/login'){throttle(attempts,ip,8,15*60*1000);if(typeof b.password!=='string'||b.password.length>256)fail('Неверный пароль',401);const hash=crypto.scryptSync(b.password,credentials.salt,64);if(!crypto.timingSafeEqual(hash,Buffer.from(credentials.hash,'hex')))fail('Неверный пароль',401);attempts.delete(ip);if(s)sessions.delete(s.token);const token=crypto.randomBytes(32).toString('base64url');sessions.set(token,{expires:Date.now()+duration});return send(res,200,{state:view(true),admin:true},{'Set-Cookie':cookie(token,duration/1000)})}
if(url.pathname==='/api/logout'){if(s)sessions.delete(s.token);return send(res,200,{state:view(false),admin:false},{'Set-Cookie':cookie('',0)})}
if(url.pathname==='/api/register'){throttle(registrations,ip,30,60*60*1000);if(state.rounds)fail('Регистрация закрыта');const {name,nick}=b,tag=typeof b.tag==='string'?'#'+b.tag.trim().replace(/^#/,'').toUpperCase():'';if(typeof name!=='string'||!name.trim()||name.length>50||typeof nick!=='string'||!nick.trim()||nick.length>40||!/^#[A-Z0-9]{3,19}$/.test(tag))fail('Проверьте имя, ник и тег игрока');if(state.players.some(p=>p.tag===tag))fail('Игрок с таким тегом уже зарегистрирован');const friend=friendship(b);const next=structuredClone(state);next.players.push({id:crypto.randomUUID(),name:name.trim(),nick:nick.trim(),tag,...friend});persist(next);return send(res,200,{state:view(!!s),admin:!!s})}
if(!s)fail('Войдите как организатор',401);
if(url.pathname==='/api/action'){change(b);return send(res,200,{state:view(true),admin:true})}
if(url.pathname==='/api/password'){if(typeof b.current!=='string'||b.current.length>256||!crypto.timingSafeEqual(crypto.scryptSync(b.current,credentials.salt,64),Buffer.from(credentials.hash,'hex')))fail('Текущий пароль неверен',400);if(typeof b.password!=='string'||b.password.length<12||b.password.length>256)fail('Новый пароль: от 12 до 256 символов');const salt=crypto.randomBytes(16).toString('hex');credentials={salt,hash:crypto.scryptSync(b.password,salt,64).toString('hex')};fs.writeFileSync(authFile,JSON.stringify(credentials),{mode:0o600});fs.writeFileSync(path.join(dataDir,'admin-access.txt'),'Пароль изменён организатором. Используйте новый пароль.\n',{mode:0o600});sessions.clear();return send(res,200,{state:view(false),admin:false},{'Set-Cookie':cookie('',0)})}
fail('Не найдено',404)}
if(!['GET','HEAD'].includes(req.method))fail('Метод недоступен',405);
const files={'/':'index.html','/index.html':'index.html','/app.js':'app.js','/style.css':'style.css','/engine.js':'engine.js','/brand.png':'brand.png'};const file=files[url.pathname];if(!file)fail('Не найдено',404);const data=fs.readFileSync(path.join(root,file));res.setHeader('Cache-Control','no-cache');res.setHeader('Content-Type',file.endsWith('.html')?'text/html; charset=utf-8':file.endsWith('.css')?'text/css; charset=utf-8':file.endsWith('.png')?'image/png':'text/javascript; charset=utf-8');res.end(req.method==='HEAD'?undefined:data)
}catch(err){send(res,err.status||400,{error:err.status===500?'Ошибка сервера':err.message})}});
setInterval(()=>{const now=Date.now();for(const [k,v]of sessions)if(v.expires<now)sessions.delete(k);for(const map of [attempts,registrations])for(const[k,v]of map)if(v.until<now)map.delete(k)},60000).unref();
server.listen(process.env.PORT||4173,'127.0.0.1',()=>console.log(`Local: http://127.0.0.1:${process.env.PORT||4173}`));
